import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";
import { inter } from "../assets/fonts/font";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased`}>
        <Header />

        <main style={{ padding: "100px" }}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
